# Serverless Framework Configuration File

# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: diegoarca

# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-serverless

# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-serverless


provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:Scan
        - dynamodb:Query
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:888577066848:table/${self:custom.Test}
        - arn:aws:dynamodb:${self:provider.region}:888577066848:table/${self:custom.User}
        - arn:aws:dynamodb:${self:provider.region}:888577066848:table/${self:custom.Cache}

custom:
  Test: Test
  User: User
  Cache: Cache

package:
  exclude:
    - node_modules/**
    - src/**
    - tests/**
    - .gitignore
    - README.md

functions:
  Test:
    handler: src/Handle.test
    events:
      - httpApi:
          path: /test
          method: get

  CreateUser:
    handler: src/Handle.createUser
    events:
      - httpApi:
          path: /users
          method: post

  GetUsers:
    handler: src/Handle.getUsers
    events:
      - httpApi:
          path: /users
          method: get

resources:
  Resources:
    TestModel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.Test}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    UserModel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.User}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    CacheModel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.Cache}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: cacheKey
            AttributeType: S
        KeySchema:
          - AttributeName: cacheKey
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: expirationTime
          Enabled: true

